### ISSUE TITLE
update lodash dependency to fix vulnerability

### ISSUE THREAD

**Issue by unuseless** [TryGhost/express-hbs#209]
Lodash should be  >=4.17.19  .

Maybe replace lodash dependency in `package.json` (currently: `"lodash": "4.17.15"`) with `"lodash": "^4.17.19",`, i.e. adding the `^`.

**Comment by daniellockyer** [comment]
Hey @unuseless :wave: `lodash` was updated and released in 2.3.4 :slightly_smiling_face:
