### ISSUE TITLE
Security Contact Needed

### ISSUE THREAD

**Issue by agustingianni** [TryGhost/express-hbs#222]
Hello,

I am a member of the GitHub Security Lab (https://securitylab.github.com).

I've attempted to reach a maintainer for this project to report a potential security issue but have been unable to verify the report was received. Please could a project maintainer contact us at securitylab@github.com, or provide an email address so we can contact you.

Thank you,
Agustin Gianni (@agustingianni)
GitHub Security Lab

**Comment by ErisDS** [comment]
Please see the newly added https://github.com/TryGhost/express-hbs/blob/master/SECURITY.md

**Comment by agustingianni** [comment]
Fantastic thank you.
