### ISSUE TITLE
Support declarative layout in views

### ISSUE THREAD

**Issue by ghost** [TryGhost/express-hbs#67]
server.js includes the following...

```
// view engine setup
var hbs         = require('express-handlebars');
app.engine('handlebars', hbs( {
    layoutsDir: __dirname + '/app/views/layouts',
    partialsDir: __dirname + '/app/views/partials',
    defaultLayout: 'default'
}));
app.set('view engine', 'handlebars');
app.set('views', __dirname + '/app/views');
```

views/test.handlebars includes

```
{{!< notDefault }}
<h1>Not the default</h1>
```

views/templates includes two templates; default.handlebars and notDefault.handlebars.
However, when test is rendered, it always uses the default template.
If I pass the template in during render via

```
res.render('test', {layout: 'notDefault'});
```

it works as expected.  Am I missing something or is this not currently supported?  I am using express-hbs v1.1.0 and express 4.

Thanks

**Comment by renatho** [comment]
Metatribal. Did you solve your problem? I think that I have the same problem. I installed the hbs via express, but my pages are not getting the template with {{!< notDefault }} into the page.
